

export const metadata = {
  title: 'Contact',
  description: 'Generated by create next app'
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>Contact Page mein apka swagat hai {children}</body>
    </html>
  );
}