import  Mycontext  from "./Helper/Context";
import "./globals.css";

export const metadata = {
  title: 'Tarun React',
  description: 'Generated by create next app'
}

export default function RootLayout({ children }) {
  Mycontext
  return (
    <html lang="en">
      <body>
        <Mycontext>{children}</Mycontext>
      </body>
    </html>
  );
}
